// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7goJuduLPJ2lya3dnNR3N3IVsNd0EGtU',
    appId: '1:614082499515:web:b31745788556498e082a9e',
    messagingSenderId: '614082499515',
    projectId: 'cryptoapp-c0def',
    authDomain: 'cryptoapp-c0def.firebaseapp.com',
    storageBucket: 'cryptoapp-c0def.firebasestorage.app',
    measurementId: 'G-371DLXGFPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3U-AOiFLJAYFDlI_uynomeO5xXXFq3Ac',
    appId: '1:614082499515:android:72f0e2652553cadf082a9e',
    messagingSenderId: '614082499515',
    projectId: 'cryptoapp-c0def',
    storageBucket: 'cryptoapp-c0def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxitZYAsHOS9doff7R5n3i8Urd-eolW4',
    appId: '1:614082499515:ios:bd972da5ff749ea2082a9e',
    messagingSenderId: '614082499515',
    projectId: 'cryptoapp-c0def',
    storageBucket: 'cryptoapp-c0def.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxitZYAsHOS9doff7R5n3i8Urd-eolW4',
    appId: '1:614082499515:ios:bd972da5ff749ea2082a9e',
    messagingSenderId: '614082499515',
    projectId: 'cryptoapp-c0def',
    storageBucket: 'cryptoapp-c0def.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7goJuduLPJ2lya3dnNR3N3IVsNd0EGtU',
    appId: '1:614082499515:web:0e1ed46e7ffc46a9082a9e',
    messagingSenderId: '614082499515',
    projectId: 'cryptoapp-c0def',
    authDomain: 'cryptoapp-c0def.firebaseapp.com',
    storageBucket: 'cryptoapp-c0def.firebasestorage.app',
    measurementId: 'G-Z73HV67074',
  );
}
